# Generated by Django 4.2.1 on 2023-05-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PolarPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("radius", models.FloatField()),
                ("angle", models.FloatField()),
                (
                    "cartesian_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="theone.point"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                (
                    "point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="theone.point"
                    ),
                ),
            ],
        ),
    ]
